# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-24 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.URLField(blank=True, verbose_name='Source'),
        ),
    ]
