# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-24 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20151124_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='related_items',
            field=models.ManyToManyField(related_name='_item_related_items_+', to='wiki.Item'),
        ),
    ]
