# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-24 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_item_related_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='related_items',
        ),
        migrations.RemoveField(
            model_name='item',
            name='related',
        ),
        migrations.AddField(
            model_name='item',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_item_related_+', to='wiki.Item'),
        ),
    ]
