# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-16 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20151116_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='entries',
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(to='blog.Tags'),
        ),
    ]
