# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20151116_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Title'),
        ),
    ]
